### ISSUE TITLE
[Epic] OpenSSL 3.x compatibility

### ISSUE THREAD

**Issue by janbrasna** [mozilla/ssl-config-generator#260]
This is a meta issue tracking known and unknown limitations in adding support for OpenSSL 3.x changes across the existing recommendations and current configs.
```[tasklist]
### Config compatibility
- [ ] https://github.com/mozilla/ssl-config-generator/issues/188
- [ ] https://github.com/mozilla/ssl-config-generator/pull/256
- [ ] https://github.com/mozilla/ssl-config-generator/issues/125
- [ ] https://github.com/mozilla/ssl-config-generator/issues/238
- [ ] https://github.com/mozilla/ssl-config-generator/pull/263
- [ ] #270
- [ ] ^^ Restrict RFC7919 negotiated FFDHE groups? (now enabled in TLSv1.3) see #162
- [ ] https://github.com/mozilla/ssl-config-generator/pull/284
```

**Comment by gstrauss** [comment]
Please see PR #256

**Comment by janbrasna** [comment]
I'm thinking whether any additions to support https://github.com/mozilla/server-side-tls/issues/286 shouldn't be made there too, to perhaps document the OpenSSL 3.x compatibility changes being introduced here also in the upstream wiki guidelines. (At least document the SECLEVEL change for `old`, potential more RFC7919 groups negotiated, etc.)

**Comment by gstrauss** [comment]
> ^^ Restrict RFC7919 negotiated FFDHE groups? (now enabled in TLSv1.3) see
https://github.com/mozilla/ssl-config-generator/issues/162

That is a question whether or not to change the guidelines, which belongs in an issue tracking guideline change proposals.  Please either add to #162 or create a new issue.

The rest of the (actionable) linked issues have been addressed and deployed, so I am going to mark this issue completed.

If there are new follow-up issues, please file a new issue.
